import oracledb
import pandas as pd

# 1. Connect to Oracle (update with your credentials)
connection = oracledb.connect(
    user="system",
    password="0000",
    dsn="localhost:1521/ORCLPDB1"  # default DSN for Oracle XE 21c
)

cursor = connection.cursor()

# 2. Create tables if not exist
cursor.execute("""
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE banks (
        id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        name VARCHAR2(100)
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
""")

cursor.execute("""
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE reviews (
        id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        bank_id NUMBER,
        review_text CLOB,
        rating NUMBER,
        sentiment_label VARCHAR2(20),
        sentiment_score FLOAT,
        review_date DATE,
        FOREIGN KEY (bank_id) REFERENCES banks(id)
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
""")

# 3. Load data
df = pd.read_csv("final_reviews.csv")

# 4. Insert unique banks
banks = df["bank"].unique()
bank_ids = {}
for bank in banks:
    cursor.execute("INSERT INTO banks (name) VALUES (:1) RETURNING id INTO :2", [bank, cursor.var(int)])
    bank_ids[bank] = cursor.getimplicitresults()[0][0]

# 5. Insert reviews
for _, row in df.iterrows():
    cursor.execute("""
        INSERT INTO reviews (bank_id, review_text, rating, sentiment_label, sentiment_score, review_date)
        VALUES (:1, :2, :3, :4, :5, TO_DATE(:6, 'YYYY-MM-DD'))
    """, [
        bank_ids[row["bank"]],
        row["review"],
        row["rating"],
        row["sentiment_label"],
        row["sentiment_score"],
        row["date"]
    ])

# 6. Commit and close
connection.commit()
cursor.close()
connection.close()

print(" All data inserted into Oracle DB.")
